version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - backend-db:/app/instance
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend-db:
