"""Add banner_image to formations and zoom_url to modules

Revision ID: 0d3018df9d8e
Revises: d3decf0719d7
Create Date: 2025-11-11 20:43:01.181202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3018df9d8e'
down_revision = 'd3decf0719d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formation_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoom_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formations', schema=None) as batch_op:
        batch_op.drop_column('banner_image')

    with op.batch_alter_table('formation_modules', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('zoom_url')

    # ### end Alembic commands ###
